# Generated by Django 5.2.6 on 2026-01-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_orderreturn_orderreturnitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='reorder_threshold',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
