# Generated by Django 5.2.6 on 2026-01-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_expiry_date_product_reorder_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
