# Generated by Django 5.2.6 on 2026-01-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_purchaseitem_expiry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, null=True, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='conversion_factor',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='qr_payload',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='subunit',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_rate_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='piece', max_length=30),
        ),
    ]
